CREATE EXTENSION IF NOT EXISTS citext;
CREATE TABLE IF NOT EXISTS users (
    Id UUID PRIMARY KEY DEFAULT uuidv7(),
    Name VARCHAR(255) NOT NULL,
    Email CITEXT UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    PepperVersion INTEGER NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DeletedAt TIMESTAMP NULL
);